feat(buildTheme): add getBoxShadow helper
Frontify/fondue-tokens pull request #88
Opened 2022-09-06 15:06 UTC by leko91

As discussed in the [Slack convo](https://frontify.slack.com/archives/C041H8F0VEU/p1662117361995179)

2022-09-07 12:14 UTC, jonasbuechel requested changes
It's solved in an elegant way. I compared all the dist output and it only affected tailwind.config.js and no Figma output 👍 

I found two issues after running `npm run build:debug`

dist/tailwind/tailwind.config.js
```
"boxShadow": {
  "inner-line": "inset 0 0 0 var(--0.063rem) var(--rgba(8, 8, 8, 0.1)))",
  "inner-line-strong": "inset 0 0 0 var(--0.063rem) var(--rgba(8, 8, 8, 0.15)))"
} 
```
I think var() including the value is wrong here

dist/css/tailwind_unpurged.css
Does not contain the expected classes `tw-shadow-inner-line` and `tw-shadow-inner-line-strong`. I gues that's a sequence error of the one above.

2022-09-07 12:14 UTC, jonasbuechel commented on src/formatters/tailwind/buildTheme.js
> +  let object = {};
Please name that more meaningful, what does it contain?

2022-09-19 10:46 UTC, leko91 commented
@jonasbuechel @thisguyscode I fixed the variables in the build, but I cannot get the css classes to generate. Any ideas?

2022-10-03 11:57 UTC, jonasbuechel requested changes

2022-10-03 11:57 UTC, jonasbuechel commented on src/formatters/tailwind/buildTheme.js
> +    "inner-line": `inset 0 0 0 var(--${dictionary.tokens.line["width"].name}) var(--${dictionary.tokens.line["color"].name}))`,
```suggestion
    "inner-line": `inset 0 0 0 var(--${dictionary.tokens.line["width"].name}) var(--${dictionary.tokens.line["color"].name})`,
```

Superfluous ')' stops it from being integrated into the CSS output.

2022-10-03 11:57 UTC, jonasbuechel commented on src/formatters/tailwind/buildTheme.js
> +    "inner-line-strong": `inset 0 0 0 var(--${dictionary.tokens.line["width"].name}) var(--${dictionary.tokens.line["color-strong"].name}))`,
```suggestion
    "inner-line-strong": `inset 0 0 0 var(--${dictionary.tokens.line["width"].name}) var(--${dictionary.tokens.line["color-strong"].name})`,
```

Superfluous ')' stops it from being integrated into the CSS output.

2022-10-10 06:57 UTC, merged